### ISSUE TITLE
Test failed on fedora copr

### ISSUE THREAD

**Issue by ghost** [diwic/alsa-sys#8]
https://download.copr.fedorainfracloud.org/results/remilauzier/zemeroth/fedora-rawhide-x86_64/02304619-rust-alsa-sys/builder-live.log.gz

failures:

---- src/generated.rs - snd_ctl_elem_list_t (line 4803) stdout ----
error[E0425]: cannot find value `element_index` in this scope
 --> src/generated.rs:4806:1
  |
5 | element_index = snd_ctl_elem_list_get_index(&list, 2);
  | ^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `snd_ctl_elem_list_get_index` in this scope
 --> src/generated.rs:4806:17
  |
5 | element_index = snd_ctl_elem_list_get_index(&list, 2);
  |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope
  |
help: consider importing this function
  |
4 | use alsa_sys::snd_ctl_elem_list_get_index;
  |

error[E0425]: cannot find value `list` in this scope
 --> src/generated.rs:4806:46
  |
5 | element_index = snd_ctl_elem_list_get_index(&list, 2);
  |                                              ^^^^ not found in this scope

error: aborting due to 3 previous errors

**Comment by ghost** [comment]
Can I have an explanation to why it was close? Would like to know what to write in the .spec for fedora.

**Comment by ghost** [comment]
Test failed on fedora koji too. https://kojipkgs.fedoraproject.org//work/tasks/1765/71491765/build.log
Will deactivate test on fedora package.

**Comment by diwic** [comment]
> Can I have an explanation to why it was close? Would like to know what to write in the .spec for fedora.

As written in the commit, bindgen happened to generate a comment that Rust thought was a doc test, this is obviously not going to work since the comment was C code, not Rust code.

**Comment by diwic** [comment]
> Test failed on fedora koji too. https://kojipkgs.fedoraproject.org//work/tasks/1765/71491765/build.log
> Will deactivate test on fedora package.

Not sure what this does different than `cargo test`, the latter now executes 0 doctests (with the commit included that disables doctests).
