### ISSUE TITLE
Improve error message on missing pkg-conf

### ISSUE THREAD

**Issue by jonnius** [diwic/alsa-sys#9]
If pkg-conf is missing, the error message is just `No such file or directory`. A better error message would be desirable.

**Comment by diwic** [comment]
Hi,

I believe this to be a problem with the pkg-config package rather than the alsa-sys package. Do you agree?

**Comment by jonnius** [comment]
You are right and this already has been [reported](https://github.com/rust-lang/pkg-config-rs/issues/56). Thanks!
